import House1 from "./public/housesImages/house1.png";
import House2 from "./public/housesImages/house2.png";
import House3 from "./public/housesImages/house3.png";
import House4 from "./public/housesImages/house4.png";
import House5 from "./public/housesImages/house5.png";
import House6 from "./public/housesImages/house6.png";

export const data = [
  {
    id: 1,
    img: House1,
    price: 2095,
    title: "Palm Harbor",
    address: "2699 Green Valley, Highland Lake, FL",
    beds: 3,
    baths: 2,
    size: "5x7 m²",
    popular: true,
    type: 'rent',
  },
  {
    id: 2,
    img: House2,
    price: 2700,
    title: "Beverly Springfield",
    address: "2821 Lake Sevilla, Palm Harbor, TX",
    beds: 4,
    baths: 2,
    size: "6x7.5 m²",
    popular: true,
    type: 'rent',
  },
  {
    id: 3,
    img: House3,
    price: 4550,
    title: "Faulkner Ave",
    address: "909 Woodland St, Michigan, IN",
    beds: 4,
    baths: 3,
    size: "8x10 m²",
    popular: true,
    type: 'rent',
  },
  {
    id: 4,
    img: House4,
    price: 2400,
    title: "St. Crystal",
    address: "210 US Highway, Highland Lake, FL",
    beds: 4,
    baths: 2,
    size: "6x8 m²",
    popular: false,
    type: 'rent',
  },
  {
    id: 5,
    img: House5,
    price: 1500,
    title: "Cove Red",
    address: "243 Curlew Road, Palm Harbor, TX",
    beds: 2,
    baths: 1,
    size: "5x7.5 m²",
    popular: false,
    type: 'rent',
  },
  {
    id: 6,
    img: House6,
    price: 1600,
    title: "Tarpon Bay",
    address: "103 Lake Shores, Michigan, IN",
    beds: 3,
    baths: 1,
    size: "5x7 m²",
    popular: false,
    type: 'rent',
  },
  {
    id: 7,
    img: House1,
    price: 2230,
    title: "The Sunset Bay",
    address: "2699 Green Valley, Highland Lake, FL",
    beds: 3,
    baths: 2,
    size: "5x7 m²",
    popular: true,
    type: 'rent',
  },
  {
    id: 8,
    img: House2,
    price: 2620,
    title: "The Jenkins",
    address: "2852 Lake Sevilla, Palm Harbor, TX",
    beds: 3,
    baths: 2,
    size: "7x7.5 m²",
    popular: true,
    type: 'rent',
  },
  {
    id: 9,
    img: House3,
    price: 4570,
    title: "he Lago Mira",
    address: "18763 Woodland St, Michigan, IN",
    beds: 5,
    baths: 4,
    size: "8x10 m²",
    popular: true,
    type: 'rent',
  },
  {
    id: 10,
    img: House4,
    price: 3400,
    title: "Plant City",
    address: "605 S. Frontage Road, Plant City, FL 33563",
    beds: 4,
    baths: 2,
    size: "6x8 m²",
    popular: false,
    type: 'rent',
  },
  {
    id: 11,
    img: House5,
    price: 2500,
    title: "Millersburg",
    address: "3737 Palm Harbor Drive, Millersburg, OR",
    beds: 3,
    baths: 2,
    size: "6x7.5 m²",
    popular: false,
    type: 'rent',
  },
  {
    id: 12,
    img: House6,
    price: 1700,
    title: "Austin",
    address: "830 Bastrop Hwy., Austin, TX",
    beds: 3,
    baths: 1,
    size: "5x7 m²",
    popular: false,
    type: 'rent',
  },

  {
    id: 13,
    img: House1,
    price: 2198000,
    title: "Harbor Marina",
    address: "2670 Green Valley, Highland Lake, FL",
    beds: 3,
    baths: 2,
    size: "5x8 m²",
    popular: true,
    type: 'buy',
  },
  {
    id: 14,
    img: House2,
    price: 3700000,
    title: "Honeymoon Island",
    address: "2823 Lake Sevilla, Palm Harbor, TX",
    beds: 4,
    baths: 2,
    size: "6x7.5 m²",
    popular: true,
    type: 'buy',
  },
  {
    id: 15,
    img: House3,
    price: 4550000,
    title: "Hovercon Ave",
    address: "200 Woodisland St, Michigan, IN",
    beds: 4,
    baths: 3,
    size: "8x10 m²",
    popular: true,
    type: 'buy',
  },
  {
    id: 16,
    img: House4,
    price: 2400000,
    title: "St. Zerochis",
    address: "210 US Highway, Highland Lake, FL",
    beds: 4,
    baths: 2,
    size: "6x8 m²",
    popular: false,
    type: 'buy',
  },
  {
    id: 17,
    img: House5,
    price: 150000,
    title: "Cove Blue",
    address: "243 Curlew Road, Palm Harbor, TX",
    beds: 2,
    baths: 1,
    size: "5x7.5 m²",
    popular: false,
    type: 'buy',
  },
];
